In [1]:
import numpy as np

In [10]:
#Columns: [Age, Math Marks, Science Marks]
data = np.array([[18, 85, 78],
                [19, 92, 88], 
                [17, 76, 95], 
                [18, 65, 70], 
                [20, 90, 85]])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [11]:
#Get the shape of the matrix.
MatrixShape = data.shape
MatrixShape

(5, 3)

In [17]:
#Find the average age of students.
avgAgeMean = data[:,0].mean()
avgAgeMean

np.float64(18.4)

In [18]:
#Extract Math marks of all students.
mathmarks = data[:,1]
mathmarks

array([85, 92, 76, 65, 90])

In [22]:
#Find the highest Science mark.
higsciMarks = data[:,2].max()
higsciMarks

np.int64(95)

In [23]:
#Get details of the student who scored more than 90 in Math.
Morethan90 = data[:,1] > 90
Morethan90

array([False,  True, False, False, False])

In [25]:
#Increase Math marks of all students by 5.
markinc = data[:,1] + 5
markinc


array([90, 97, 81, 70, 95])

In [26]:
#Find how many students are younger than 19.
young = data[:,0] < 19
young

array([ True, False,  True,  True, False])

In [27]:
#Calculate the average marks in each subject (column-wise mean).abs
avgm = data[:,1:].mean(axis=0)
avgm

array([81.6, 83.2])

In [28]:
#Get data of students who scored at least 80 in both subjects.
both = data[(data[:,1] >= 80) & (data[:,2] >= 80)]
both

array([[19, 92, 88],
       [20, 90, 85]])