In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [4]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [5]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [6]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [7]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [9]:
arr1 % arr2

array([1, 2, 3, 4, 5])

In [10]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [12]:
arr1 * 2

array([ 2,  4,  6,  8, 10])

In [14]:
#Broadcasting
l = [10, 20, 30, 40]
arr = np.array(l)

In [15]:
arr+10

array([20, 30, 40, 50])

In [18]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [21]:
#Deep and Shallow copy
a = np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [30]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
a[4:6] * 10

array([50, 60])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a 
b = a
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [37]:
A

array([[1, 2],
       [3, 4]])

In [38]:
B

array([[5, 6],
       [7, 8]])

In [39]:
A * B

array([[ 5, 12],
       [21, 32]])

In [40]:
A @ B
#Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
A. T
#Tranpose

array([[1, 3],
       [2, 4]])

In [47]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [48]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [51]:
#Splitting abytearray
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [53]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
for i in a:
    print(i)

1
2
3
4
