In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3,4.2,"hello"]
a

[1, 2, 3, 4.2, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3', '4.2', 'hello'], dtype='<U32')

In [7]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [21]:
arr = np.linspace(1, 5, 5)
arr

array([1., 2., 3., 4., 5.])

In [23]:
np.random.rand(10)

array([0.18196323, 0.26328737, 0.44012436, 0.31884378, 0.36006512,
       0.1461519 , 0.01325511, 0.90712158, 0.53205511, 0.86464943])

In [25]:
np.random.randn(10)

array([-0.91733144,  0.5416525 , -0.45173265, -0.48128141,  0.00965454,
        1.24770519, -0.16015958, -0.57648773, -0.20227052, -0.41079923])

In [28]:
np.random.randint(10,20,5)

array([16, 17, 13, 17, 15], dtype=int32)

In [29]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.shape

(3, 3)

In [31]:
arr.size

9

In [32]:
arr.dtype

dtype('int64')

In [33]:
arr.min()

np.int64(1)

In [34]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [37]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [38]:
arr.mean()

np.float64(5.0)

In [39]:
arr.std()

np.float64(2.581988897471611)

In [40]:
arr.argmax()

np.int64(8)

In [41]:
arr.argmin()

np.int64(0)

In [42]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [44]:
arr.shape

(30,)

In [48]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [49]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])